### ISSUE TITLE
LDAP doesn't come up after server shutdown or similar

### ISSUE THREAD

**Issue by StigLau** [altran/_Whydah-UserIdentityBackend#32]
If all hell brakes lose, LDAP goes down and can't come up.
Restarting the hosting server with running ApacheDS doesn't work, and the init.d script also.

Manual steps after server downtime:
Delete pid if 'apache already started' /var/lib/apacheds-2.0.0_M16/default/run/apacheds-default.pid
Start:
sudo /opt/apacheds-2.0.0_M16/bin/apacheds start default

You should be able to telnet localhost 10389 and get a response

**Comment by sherriff** [comment]
moved
