### ISSUE TITLE
Modernize and improve  import functionality

### ISSUE THREAD

**Issue by sherriff** [altran/_Whydah-UserIdentityBackend#41]
1. Replace apache.commons.dbutils with spring-jdbc for importers. Dependency should be removed afterwards. 
2. Move all SQL queries to Daos. 
3. Verify that Flyway-change did not break import functionality,  #44. 
4. Ensure import functionality is safe. 
Always run import functionality. 
Ensure import functionality adds missing data, but never overwrites or removes existing data. 
Add properties to delete ldap or db data on disk. Default disabled.

In the future import functionality should support import both from CSV and from data from an HTTP endpoint, but that will be a new issue.

**Comment by totto** [comment]
move import/export to UAWA... and just provision the super-admin is probably better

**Comment by sherriff** [comment]
moved
