### ISSUE TITLE
New requirements for Whydah 2.1

### ISSUE THREAD

**Issue by totto** [altran/_Whydah-UserIdentityBackend#42]
New requirements for Whydah 2.1:

Security
* minimum securitylevel
* allowed DEFCON levels
* prioritized list of crypto algorithms
* bootstrap crypto dataset

Roles
* registered application roles

API's
* Add role to application
* Add organization to application
* Add/Edit crypto algorithms for application
* Update applicationsecret for Application

**Comment by sherriff** [comment]
moved
