### ISSUE TITLE
LDAP issue

### ISSUE THREAD

**Issue by totto** [altran/_Whydah-UserIdentityBackend#48]
observed timeout of certain LDAP requests in some circumstances. Miight be connected to attribute search on parminantly locked accounts   (i.e. failed too many password/new passwords attempts..   
Environment:  ApacheSD  (ads-pwdMaxFailure	5)

Trace
09:53:58.203 [Grizzly(1)] INFO  n.w.i.user.resource.PasswordResource - Started: PasswordResource
09:53:58.203 [Grizzly(1)] INFO  n.w.i.user.resource.PasswordResource - Reset password (POST) for username=myusername
09:53:58.203 [Grizzly(1)] TRACE n.w.i.u.identity.LdapUserIdentityDao - getUserAttributesForUsername using initials=myusername
09:53:58.203 [Grizzly(1)] TRACE n.w.i.u.identity.LdapUserIdentityDao - NamingException. usernameAttribute initials, username myusername
09:53:58.204 [Grizzly(1)] ERROR n.w.i.user.resource.PasswordResource - resetPassword failed
javax.naming.CommunicationException: Connection timed out
    at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:2003) ~[na:1.7.0_71]
    at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1847) ~[na:1.7.0_71]
    at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1772) ~[na:1.7.0_71]
    at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:386) ~[na:1.7.0_71]
    at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:356) ~[na:1.7.0_71]
    at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:339) ~[na:1.7.0_71]
    at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267) ~[na:1.7.0_71]
    at net.whydah.identity.user.identity.LdapUserIdentityDao.getUserAttributesForUsername(LdapUserIdentityDao.java:316) ~[UserIdentityBackend-2.0.1.Final.jar:na]

After UIB restart:
10:42:32.759 [Grizzly(1)] TRACE n.w.identity.security.SecurityFilter - filter path /password/9bf31c7ff062936a96d3c8bd1f8f2ff3/reset/username/ivarh
10:42:32.765 [Grizzly(1)] TRACE n.w.identity.security.SecurityFilter - application verified /9bf31c7ff062936a96d3c8bd1f8f2ff3. Moving to next in chain.
10:42:32.832 [Grizzly(1)] INFO  n.w.i.user.resource.PasswordResource - Started: PasswordResource
10:42:32.834 [Grizzly(1)] INFO  n.w.i.user.resource.PasswordResource - Reset password (POST) for username=myuser
10:42:32.851 [Grizzly(1)] TRACE n.w.i.u.identity.LdapUserIdentityDao - getUserAttributesForUsername using initials=myuser
10:42:32.860 [Grizzly(1)] TRACE n.w.i.u.identity.LdapUserIdentityDao - getUserAttributesForUsername using initials=myuser
10:42:32.864 [Grizzly(1)] TRACE n.w.i.u.identity.LdapUserIdentityDao - getUserAttributesForUsername using initials=myuser
10:42:33.544 [Grizzly(1)] INFO  n.w.i.user.email.PasswordSender - Sending resetPassword email for user myuser to myuser@mail, token=aXZhcmg6MTQyMTY2NDE1MzU0MzpJQmtQR2xBb1BVWWNEeXRXYlFNK0hSTVdiQWRuZHdNS013d0JiblVTR3owUEJSd0tmUzhEUUJ3MkpFMTJBaVUv

and then..

10:43:02.385 [Grizzly(1)] TRACE n.w.i.u.identity.LdapAuthenticator - findUserDN with username=myusername found userDN=uid=aa717c39-1666-45e6-9d74-80151e53d9ba,ou=users,dc=external,dc=WHYDAH,dc=no
10:43:02.415 [Grizzly(1)] TRACE n.w.i.u.identity.LdapAuthenticator - authenticateUser failed (returned null), because AuthenticationException: [LDAP: error code 49 - INVALID_CREDENTIALS: Bind failed: account was permanently locked]

**Comment by sherriff** [comment]
moved
