### ISSUE TITLE
Improve property loading to support config_override from file

### ISSUE THREAD

**Issue by sherriff** [altran/_Whydah-UserIdentityBackend#50]
Goal: 
a. Support templates for different modes (prod-ha, prod, dev, etc.) 
b. Possible to override configuration using file outside jarfile. 
c. Make as many properties as possible default and keep the override file as small as possible. 

Suggested changes: 
1. Replace custom AppConfig with Constretto (Spring is optional).

2. Ensure templates are updated in Git and make the necessary changes to Ansible scripts to reduce the number of changes Ansible must perform from defaults. This will reduce the problem of "keeping properties in several locations" as most of the properties will be default. I expect only prod and prod-HA templates to be used in any environments. TEST-template for UIB might be useful where UIB integrates with external services, but use embedded LDAP and database. 

3. Make a copy (at startup) to an config_examples directory outside the jar file. Example _copyPropertyFilesToExampleFolder_. Ask Stig or Erik to get a copy of the latest AppConfig.java in use for an example. 

4. Ensure it is possible to get the resolved properties printed in the log in an easy way. 

5. If the new strategy works better than the old one, write issues for the other Whydah components with reference to documentation in wiki explaining it. Consider removing the TEST-template in the other components since the have no integration with persistent storage.

**Comment by totto** [comment]
We have to ensure that the solution does not contain too much "magic" as it send the users barking up the wrong trees, i.e. it should be explicit to the user what a property-value is resolved to runtime

**Comment by maurtvedt** [comment]
Suggestion on startup: append as comments to override config file the inherited configuration parameters from templates.
