### ISSUE TITLE
Review av shellscript

### ISSUE THREAD

**Issue by maurtvedt** [altran/_Whydah-UserIdentityBackend#51]
- Shellscript for oppdater og restart av komponenter
- Ikke last ned ny versjon hvis det ikke finnes ny versjon på nexus
- Skal kille evt kjørende prosesser og starte en ny (garantert)
- Må starte med riktig bruker (Run as user)
- På bruker pekes til startupscript som ligger på init.c

For alle whydah-komponenter og provisjoneringsscript.

**Comment by sherriff** [comment]
moved
